// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (project_id, filename, content_type, size_bytes, storage_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, issue_id, comment_id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at
`

type CreateAttachmentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	StorageKey  string      `json:"storage_key"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ProjectID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.CommentID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, issue_id, comment_id, project_id, filename, content_type, size_bytes, storage_key, uploaded_by, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.CommentID,
		&i.ProjectID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectAttachments = `-- name: ListProjectAttachments :many
SELECT a.id, a.issue_id, a.comment_id, a.project_id, a.filename, a.content_type, a.size_bytes, a.storage_key, a.uploaded_by, a.created_at, u.name AS uploaded_by_name
FROM attachments a
JOIN users u ON u.id = a.uploaded_by
WHERE a.project_id = $1
ORDER BY a.created_at DESC
`

type ListProjectAttachmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	IssueID        pgtype.UUID        `json:"issue_id"`
	CommentID      pgtype.UUID        `json:"comment_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Filename       string             `json:"filename"`
	ContentType    string             `json:"content_type"`
	SizeBytes      int64              `json:"size_bytes"`
	StorageKey     string             `json:"storage_key"`
	UploadedBy     pgtype.UUID        `json:"uploaded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UploadedByName string             `json:"uploaded_by_name"`
}

func (q *Queries) ListProjectAttachments(ctx context.Context, projectID pgtype.UUID) ([]ListProjectAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectAttachments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectAttachmentsRow
	for rows.Next() {
		var i ListProjectAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.CommentID,
			&i.ProjectID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
