// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (issue_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, issue_id, author_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID  pgtype.UUID `json:"issue_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.IssueID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT c.id, c.issue_id, c.author_id, c.body, c.created_at, c.updated_at, u.name AS author_name
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.id = $1
`

type GetCommentRow struct {
	ID         pgtype.UUID        `json:"id"`
	IssueID    pgtype.UUID        `json:"issue_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	AuthorName string             `json:"author_name"`
}

func (q *Queries) GetComment(ctx context.Context, id pgtype.UUID) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT c.id, c.issue_id, c.author_id, c.body, c.created_at, c.updated_at, u.name AS author_name
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.issue_id = $1
ORDER BY c.created_at ASC, c.id ASC
`

type ListIssueCommentsRow struct {
	ID         pgtype.UUID        `json:"id"`
	IssueID    pgtype.UUID        `json:"issue_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	AuthorName string             `json:"author_name"`
}

func (q *Queries) ListIssueComments(ctx context.Context, issueID pgtype.UUID) ([]ListIssueCommentsRow, error) {
	rows, err := q.db.Query(ctx, listIssueComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueCommentsRow
	for rows.Next() {
		var i ListIssueCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
