// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCycles = `-- name: ListCycles :many
SELECT
    c.id, c.team_id, c.number, c.start_date, c.end_date,
    count(i.id)::int AS issue_count,
    count(i.id) FILTER (WHERE i.status = 'done')::int AS done_count,
    (current_date BETWEEN c.start_date AND c.end_date)::boolean AS active
FROM cycles c
LEFT JOIN issues i ON i.cycle_id = c.id
WHERE c.team_id = $1
GROUP BY c.id
ORDER BY c.number DESC
`

type ListCyclesRow struct {
	ID         pgtype.UUID `json:"id"`
	TeamID     pgtype.UUID `json:"team_id"`
	Number     int32       `json:"number"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	IssueCount int32       `json:"issue_count"`
	DoneCount  int32       `json:"done_count"`
	Active     bool        `json:"active"`
}

func (q *Queries) ListCycles(ctx context.Context, teamID pgtype.UUID) ([]ListCyclesRow, error) {
	rows, err := q.db.Query(ctx, listCycles, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCyclesRow
	for rows.Next() {
		var i ListCyclesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Number,
			&i.StartDate,
			&i.EndDate,
			&i.IssueCount,
			&i.DoneCount,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
