// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssueHistory = `-- name: CreateIssueHistory :one
INSERT INTO issue_history (issue_id, actor_id, action, changes)
VALUES ($1, $2, $3, $4)
RETURNING id, issue_id, actor_id, action, changes, created_at
`

type CreateIssueHistoryParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	ActorID pgtype.UUID `json:"actor_id"`
	Action  string      `json:"action"`
	Changes []byte      `json:"changes"`
}

func (q *Queries) CreateIssueHistory(ctx context.Context, arg CreateIssueHistoryParams) (IssueHistory, error) {
	row := q.db.QueryRow(ctx, createIssueHistory,
		arg.IssueID,
		arg.ActorID,
		arg.Action,
		arg.Changes,
	)
	var i IssueHistory
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ActorID,
		&i.Action,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const listIssueHistory = `-- name: ListIssueHistory :many
SELECT
    h.id,
    h.issue_id,
    h.actor_id,
    COALESCE(u.name, 'Deleted user') AS actor_name,
    h.action,
    h.changes,
    h.created_at
FROM issue_history h
LEFT JOIN users u ON u.id = h.actor_id
WHERE h.issue_id = $1
ORDER BY h.created_at DESC, h.id DESC
`

type ListIssueHistoryRow struct {
	ID        pgtype.UUID        `json:"id"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ActorName string             `json:"actor_name"`
	Action    string             `json:"action"`
	Changes   []byte             `json:"changes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListIssueHistory(ctx context.Context, issueID pgtype.UUID) ([]ListIssueHistoryRow, error) {
	rows, err := q.db.Query(ctx, listIssueHistory, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueHistoryRow
	for rows.Next() {
		var i ListIssueHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
