// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
WITH next_num AS (
    UPDATE teams SET next_issue_number = next_issue_number + 1
    WHERE id = $1
    RETURNING next_issue_number - 1 AS number
)
INSERT INTO issues (team_id, number, title, description, priority, assignee_id, project_id, created_by)
SELECT $1, next_num.number, $2, $3, $4, $5, $6, $7
FROM next_num
RETURNING id, team_id, number, title, description, status, priority, assignee_id, parent_id, project_id, cycle_id, due_date, created_by, created_at, updated_at
`

type CreateIssueParams struct {
	TeamID      pgtype.UUID `json:"team_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Priority    int16       `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssigneeID,
		arg.ProjectID,
		arg.CreatedBy,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ParentID,
		&i.ProjectID,
		&i.CycleID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT
    i.id, i.team_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.parent_id, i.project_id, i.cycle_id, i.due_date, i.created_by, i.created_at, i.updated_at,
    t.key AS team_key,
    u.name AS assignee_name,
    p.name AS project_name,
    lbl.id AS label_id,
    COALESCE(lbl.name, '') AS label_name,
    COALESCE(lbl.color, '') AS label_color
FROM issues i
JOIN teams t ON t.id = i.team_id
LEFT JOIN users u ON u.id = i.assignee_id
LEFT JOIN projects p ON p.id = i.project_id
LEFT JOIN LATERAL (
    SELECT l.id, l.name, l.color
    FROM issue_labels il
    JOIN labels l ON l.id = il.label_id
    WHERE il.issue_id = i.id
    ORDER BY l.name
    LIMIT 1
) lbl ON true
WHERE i.id = $1
`

type GetIssueRow struct {
	ID           pgtype.UUID        `json:"id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Number       int32              `json:"number"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	Priority     int16              `json:"priority"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	CycleID      pgtype.UUID        `json:"cycle_id"`
	DueDate      pgtype.Date        `json:"due_date"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TeamKey      string             `json:"team_key"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
	ProjectName  pgtype.Text        `json:"project_name"`
	LabelID      pgtype.UUID        `json:"label_id"`
	LabelName    string             `json:"label_name"`
	LabelColor   string             `json:"label_color"`
}

func (q *Queries) GetIssue(ctx context.Context, id pgtype.UUID) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, id)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ParentID,
		&i.ProjectID,
		&i.CycleID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamKey,
		&i.AssigneeName,
		&i.ProjectName,
		&i.LabelID,
		&i.LabelName,
		&i.LabelColor,
	)
	return i, err
}

const getIssueByNumber = `-- name: GetIssueByNumber :one
SELECT
    i.id, i.team_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.parent_id, i.project_id, i.cycle_id, i.due_date, i.created_by, i.created_at, i.updated_at,
    t.key AS team_key,
    u.name AS assignee_name,
    p.name AS project_name,
    lbl.id AS label_id,
    COALESCE(lbl.name, '') AS label_name,
    COALESCE(lbl.color, '') AS label_color
FROM issues i
JOIN teams t ON t.id = i.team_id
LEFT JOIN users u ON u.id = i.assignee_id
LEFT JOIN projects p ON p.id = i.project_id
LEFT JOIN LATERAL (
    SELECT l.id, l.name, l.color
    FROM issue_labels il
    JOIN labels l ON l.id = il.label_id
    WHERE il.issue_id = i.id
    ORDER BY l.name
    LIMIT 1
) lbl ON true
WHERE i.team_id = $1 AND i.number = $2
`

type GetIssueByNumberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	Number int32       `json:"number"`
}

type GetIssueByNumberRow struct {
	ID           pgtype.UUID        `json:"id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Number       int32              `json:"number"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	Priority     int16              `json:"priority"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	CycleID      pgtype.UUID        `json:"cycle_id"`
	DueDate      pgtype.Date        `json:"due_date"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TeamKey      string             `json:"team_key"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
	ProjectName  pgtype.Text        `json:"project_name"`
	LabelID      pgtype.UUID        `json:"label_id"`
	LabelName    string             `json:"label_name"`
	LabelColor   string             `json:"label_color"`
}

func (q *Queries) GetIssueByNumber(ctx context.Context, arg GetIssueByNumberParams) (GetIssueByNumberRow, error) {
	row := q.db.QueryRow(ctx, getIssueByNumber, arg.TeamID, arg.Number)
	var i GetIssueByNumberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ParentID,
		&i.ProjectID,
		&i.CycleID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamKey,
		&i.AssigneeName,
		&i.ProjectName,
		&i.LabelID,
		&i.LabelName,
		&i.LabelColor,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT
    i.id, i.team_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.parent_id, i.project_id, i.cycle_id, i.due_date, i.created_by, i.created_at, i.updated_at,
    t.key AS team_key,
    u.name AS assignee_name,
    p.name AS project_name,
    lbl.id AS label_id,
    COALESCE(lbl.name, '') AS label_name,
    COALESCE(lbl.color, '') AS label_color
FROM issues i
JOIN teams t ON t.id = i.team_id
LEFT JOIN users u ON u.id = i.assignee_id
LEFT JOIN projects p ON p.id = i.project_id
LEFT JOIN LATERAL (
    SELECT l.id, l.name, l.color
    FROM issue_labels il
    JOIN labels l ON l.id = il.label_id
    WHERE il.issue_id = i.id
    ORDER BY l.name
    LIMIT 1
) lbl ON true
WHERE i.team_id = $1
  AND ($2::text IS NULL OR i.status = $2)
  AND ($3::uuid IS NULL OR i.project_id = $3)
  AND ($4::uuid IS NULL OR i.cycle_id = $4)
  AND ($5::uuid IS NULL OR i.assignee_id = $5)
  AND ($6::smallint IS NULL OR i.priority = $6)
  AND (
    $7::uuid IS NULL
    OR EXISTS (SELECT 1 FROM issue_labels il2 WHERE il2.issue_id = i.id AND il2.label_id = $7)
  )
ORDER BY i.created_at DESC
`

type ListIssuesParams struct {
	TeamID     pgtype.UUID `json:"team_id"`
	Status     pgtype.Text `json:"status"`
	ProjectID  pgtype.UUID `json:"project_id"`
	CycleID    pgtype.UUID `json:"cycle_id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
	Priority   pgtype.Int2 `json:"priority"`
	LabelID    pgtype.UUID `json:"label_id"`
}

type ListIssuesRow struct {
	ID           pgtype.UUID        `json:"id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Number       int32              `json:"number"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	Priority     int16              `json:"priority"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	CycleID      pgtype.UUID        `json:"cycle_id"`
	DueDate      pgtype.Date        `json:"due_date"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TeamKey      string             `json:"team_key"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
	ProjectName  pgtype.Text        `json:"project_name"`
	LabelID      pgtype.UUID        `json:"label_id"`
	LabelName    string             `json:"label_name"`
	LabelColor   string             `json:"label_color"`
}

func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.TeamID,
		arg.Status,
		arg.ProjectID,
		arg.CycleID,
		arg.AssigneeID,
		arg.Priority,
		arg.LabelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesRow
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.ParentID,
			&i.ProjectID,
			&i.CycleID,
			&i.DueDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamKey,
			&i.AssigneeName,
			&i.ProjectName,
			&i.LabelID,
			&i.LabelName,
			&i.LabelColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueDetails = `-- name: UpdateIssueDetails :one
UPDATE issues SET
    title = $2,
    description = $3,
    priority = $4,
    assignee_id = $5,
    project_id = $6,
    cycle_id = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, team_id, number, title, description, status, priority, assignee_id, parent_id, project_id, cycle_id, due_date, created_by, created_at, updated_at
`

type UpdateIssueDetailsParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Priority    int16       `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	CycleID     pgtype.UUID `json:"cycle_id"`
}

func (q *Queries) UpdateIssueDetails(ctx context.Context, arg UpdateIssueDetailsParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueDetails,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssigneeID,
		arg.ProjectID,
		arg.CycleID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ParentID,
		&i.ProjectID,
		&i.CycleID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE issues SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, team_id, number, title, description, status, priority, assignee_id, parent_id, project_id, cycle_id, due_date, created_by, created_at, updated_at
`

type UpdateIssueStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueStatus, arg.ID, arg.Status)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ParentID,
		&i.ProjectID,
		&i.CycleID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
