// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIssueBlocker = `-- name: AddIssueBlocker :execrows
INSERT INTO issue_relations (issue_id, related_issue_id, type)
VALUES ($1, $2, 'blocks')
ON CONFLICT (issue_id, related_issue_id, type) DO NOTHING
`

type AddIssueBlockerParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) AddIssueBlocker(ctx context.Context, arg AddIssueBlockerParams) (int64, error) {
	result, err := q.db.Exec(ctx, addIssueBlocker, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const doesIssueBlockTransitively = `-- name: DoesIssueBlockTransitively :one
WITH RECURSIVE chain AS (
    SELECT ir.related_issue_id AS id FROM issue_relations ir WHERE ir.issue_id = $2 AND ir.type = 'blocks'
    UNION
    SELECT r.related_issue_id FROM issue_relations r JOIN chain c ON r.issue_id = c.id WHERE r.type = 'blocks'
)
SELECT ($1::uuid IN (SELECT chain.id FROM chain))::bool AS found
`

type DoesIssueBlockTransitivelyParams struct {
	ToID   pgtype.UUID `json:"to_id"`
	FromID pgtype.UUID `json:"from_id"`
}

// DoesIssueBlockTransitively reports whether sqlc.arg(from_id) already blocks
// sqlc.arg(to_id), directly or through a chain. Adding the reverse edge
// would create a dependency cycle.
func (q *Queries) DoesIssueBlockTransitively(ctx context.Context, arg DoesIssueBlockTransitivelyParams) (bool, error) {
	row := q.db.QueryRow(ctx, doesIssueBlockTransitively, arg.ToID, arg.FromID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const isIssueInAncestry = `-- name: IsIssueInAncestry :one
WITH RECURSIVE ancestry AS (
    SELECT issues.id, issues.parent_id FROM issues WHERE issues.id = $2
    UNION
    SELECT i.id, i.parent_id FROM issues i JOIN ancestry a ON i.id = a.parent_id
)
SELECT ($1::uuid IN (SELECT ancestry.id FROM ancestry))::bool AS found
`

type IsIssueInAncestryParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	StartID pgtype.UUID `json:"start_id"`
}

// IsIssueInAncestry reports whether sqlc.arg(issue_id) is the issue
// sqlc.arg(start_id) or one of its ancestors. Used to reject parent cycles:
// the proposed parent must not descend from the issue being re-parented.
func (q *Queries) IsIssueInAncestry(ctx context.Context, arg IsIssueInAncestryParams) (bool, error) {
	row := q.db.QueryRow(ctx, isIssueInAncestry, arg.IssueID, arg.StartID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const listIssueLinks = `-- name: ListIssueLinks :many
SELECT kind, id, team_key, number, title, status FROM (
    SELECT 'parent'::text AS kind, p.id, t.key AS team_key, p.number, p.title, p.status
    FROM issues c
    JOIN issues p ON p.id = c.parent_id
    JOIN teams t ON t.id = p.team_id
    WHERE c.id = $1
  UNION ALL
    SELECT 'child'::text, c.id, t.key, c.number, c.title, c.status
    FROM issues c
    JOIN teams t ON t.id = c.team_id
    WHERE c.parent_id = $1
  UNION ALL
    SELECT 'blocked_by'::text, b.id, t.key, b.number, b.title, b.status
    FROM issue_relations r
    JOIN issues b ON b.id = r.issue_id
    JOIN teams t ON t.id = b.team_id
    WHERE r.related_issue_id = $1 AND r.type = 'blocks'
  UNION ALL
    SELECT 'blocks'::text, b.id, t.key, b.number, b.title, b.status
    FROM issue_relations r
    JOIN issues b ON b.id = r.related_issue_id
    JOIN teams t ON t.id = b.team_id
    WHERE r.issue_id = $1 AND r.type = 'blocks'
) links
ORDER BY kind, number
`

type ListIssueLinksRow struct {
	Kind    string      `json:"kind"`
	ID      pgtype.UUID `json:"id"`
	TeamKey string      `json:"team_key"`
	Number  int32       `json:"number"`
	Title   string      `json:"title"`
	Status  string      `json:"status"`
}

func (q *Queries) ListIssueLinks(ctx context.Context, id pgtype.UUID) ([]ListIssueLinksRow, error) {
	rows, err := q.db.Query(ctx, listIssueLinks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueLinksRow
	for rows.Next() {
		var i ListIssueLinksRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.TeamKey,
			&i.Number,
			&i.Title,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIssueBlocker = `-- name: RemoveIssueBlocker :execrows
DELETE FROM issue_relations
WHERE issue_id = $1 AND related_issue_id = $2 AND type = 'blocks'
`

type RemoveIssueBlockerParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) RemoveIssueBlocker(ctx context.Context, arg RemoveIssueBlockerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeIssueBlocker, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIssueParent = `-- name: SetIssueParent :one
UPDATE issues SET parent_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, team_id, number, title, description, status, priority, assignee_id, parent_id, project_id, cycle_id, due_date, created_by, created_at, updated_at
`

type SetIssueParentParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) SetIssueParent(ctx context.Context, arg SetIssueParentParams) (Issue, error) {
	row := q.db.QueryRow(ctx, setIssueParent, arg.ID, arg.ParentID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.ParentID,
		&i.ProjectID,
		&i.CycleID,
		&i.DueDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
