// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIssueLabel = `-- name: AddIssueLabel :exec
INSERT INTO issue_labels (issue_id, label_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddIssueLabelParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

func (q *Queries) AddIssueLabel(ctx context.Context, arg AddIssueLabelParams) error {
	_, err := q.db.Exec(ctx, addIssueLabel, arg.IssueID, arg.LabelID)
	return err
}

const clearIssueLabels = `-- name: ClearIssueLabels :exec
DELETE FROM issue_labels WHERE issue_id = $1
`

func (q *Queries) ClearIssueLabels(ctx context.Context, issueID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearIssueLabels, issueID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (team_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, team_id, name, color
`

type CreateLabelParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	Name   string      `json:"name"`
	Color  string      `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.TeamID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const listLabels = `-- name: ListLabels :many
SELECT id, team_id, name, color FROM labels
WHERE team_id = $1 OR team_id IS NULL
ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, teamID pgtype.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
