// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLabels = `-- name: ListLabels :many
SELECT id, team_id, name, color FROM labels
WHERE team_id = $1 OR team_id IS NULL
ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, teamID pgtype.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listLabels, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
