// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Attachment struct {
	ID          pgtype.UUID        `json:"id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	CommentID   pgtype.UUID        `json:"comment_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	StorageKey  string             `json:"storage_key"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CommentMention struct {
	CommentID pgtype.UUID `json:"comment_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type Cycle struct {
	ID        pgtype.UUID `json:"id"`
	TeamID    pgtype.UUID `json:"team_id"`
	Number    int32       `json:"number"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GitLink struct {
	ID        pgtype.UUID        `json:"id"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	Provider  string             `json:"provider"`
	PrUrl     string             `json:"pr_url"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID          pgtype.UUID        `json:"id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	Number      int32              `json:"number"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      string             `json:"status"`
	Priority    int16              `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CycleID     pgtype.UUID        `json:"cycle_id"`
	DueDate     pgtype.Date        `json:"due_date"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IssueLabel struct {
	IssueID pgtype.UUID `json:"issue_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

type IssueRelation struct {
	ID             pgtype.UUID `json:"id"`
	IssueID        pgtype.UUID `json:"issue_id"`
	RelatedIssueID pgtype.UUID `json:"related_issue_id"`
	Type           string      `json:"type"`
}

type Label struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
	Name   string      `json:"name"`
	Color  string      `json:"color"`
}

type Milestone struct {
	ID         pgtype.UUID `json:"id"`
	ProjectID  pgtype.UUID `json:"project_id"`
	Name       string      `json:"name"`
	TargetDate pgtype.Date `json:"target_date"`
	SortOrder  int32       `json:"sort_order"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	CommentID pgtype.UUID        `json:"comment_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	LeadID      pgtype.UUID        `json:"lead_id"`
	TargetDate  pgtype.Date        `json:"target_date"`
	Priority    int16              `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Team struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Key             string             `json:"key"`
	NextIssueNumber int32              `json:"next_issue_number"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TeamMember struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Role         string             `json:"role"`
	GithubID     pgtype.Text        `json:"github_id"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type View struct {
	ID         pgtype.UUID        `json:"id"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	Name       string             `json:"name"`
	Definition []byte             `json:"definition"`
	Shared     bool               `json:"shared"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Webhook struct {
	ID         pgtype.UUID        `json:"id"`
	TargetUrl  string             `json:"target_url"`
	Secret     string             `json:"secret"`
	EventTypes []string           `json:"event_types"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID            pgtype.UUID        `json:"id"`
	WebhookID     pgtype.UUID        `json:"webhook_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WorkLog struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Source    string             `json:"source"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
