// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (team_id, name, description, status)
VALUES ($1, $2, $3, 'planned')
RETURNING id, team_id, name, description, status, created_at
`

type CreateProjectParams struct {
	TeamID      pgtype.UUID `json:"team_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.TeamID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT
    p.id, p.team_id, p.name, p.description, p.status, p.created_at,
    count(i.id)::int AS issue_count,
    count(i.id) FILTER (WHERE i.status = 'done')::int AS done_count
FROM projects p
LEFT JOIN issues i ON i.project_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type GetProjectRow struct {
	ID          pgtype.UUID        `json:"id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IssueCount  int32              `json:"issue_count"`
	DoneCount   int32              `json:"done_count"`
}

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.IssueCount,
		&i.DoneCount,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id, p.team_id, p.name, p.description, p.status, p.created_at,
    count(i.id)::int AS issue_count,
    count(i.id) FILTER (WHERE i.status = 'done')::int AS done_count
FROM projects p
LEFT JOIN issues i ON i.project_id = p.id
WHERE p.team_id = $1
GROUP BY p.id
ORDER BY p.created_at
`

type ListProjectsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IssueCount  int32              `json:"issue_count"`
	DoneCount   int32              `json:"done_count"`
}

func (q *Queries) ListProjects(ctx context.Context, teamID pgtype.UUID) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.IssueCount,
			&i.DoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
