// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_guide_fragments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectGuideFragment = `-- name: AddProjectGuideFragment :one
INSERT INTO project_guide_fragments (project_id, fragment_id, name, content, base_version, position)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    COALESCE((SELECT max(position) + 1 FROM project_guide_fragments WHERE project_id = $1), 0)
)
RETURNING id, project_id, fragment_id, name, content, base_version, locally_modified, position, created_at, updated_at
`

type AddProjectGuideFragmentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	FragmentID  pgtype.UUID `json:"fragment_id"`
	Name        string      `json:"name"`
	Content     string      `json:"content"`
	BaseVersion pgtype.Int4 `json:"base_version"`
}

func (q *Queries) AddProjectGuideFragment(ctx context.Context, arg AddProjectGuideFragmentParams) (ProjectGuideFragment, error) {
	row := q.db.QueryRow(ctx, addProjectGuideFragment,
		arg.ProjectID,
		arg.FragmentID,
		arg.Name,
		arg.Content,
		arg.BaseVersion,
	)
	var i ProjectGuideFragment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FragmentID,
		&i.Name,
		&i.Content,
		&i.BaseVersion,
		&i.LocallyModified,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectGuideFragment = `-- name: DeleteProjectGuideFragment :exec
DELETE FROM project_guide_fragments WHERE id = $1
`

func (q *Queries) DeleteProjectGuideFragment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectGuideFragment, id)
	return err
}

const listProjectGuideFragments = `-- name: ListProjectGuideFragments :many
SELECT id, project_id, fragment_id, name, content, base_version, locally_modified, position, created_at, updated_at FROM project_guide_fragments
WHERE project_id = $1
ORDER BY position
`

func (q *Queries) ListProjectGuideFragments(ctx context.Context, projectID pgtype.UUID) ([]ProjectGuideFragment, error) {
	rows, err := q.db.Query(ctx, listProjectGuideFragments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGuideFragment
	for rows.Next() {
		var i ProjectGuideFragment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FragmentID,
			&i.Name,
			&i.Content,
			&i.BaseVersion,
			&i.LocallyModified,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushFragmentUpdate = `-- name: PushFragmentUpdate :many
UPDATE project_guide_fragments SET
    name = $2,
    content = $3,
    base_version = $4,
    locally_modified = false,
    updated_at = now()
WHERE fragment_id = $1 AND id = ANY($5::uuid[]) AND locally_modified = false
RETURNING id, project_id, fragment_id, name, content, base_version, locally_modified, position, created_at, updated_at
`

type PushFragmentUpdateParams struct {
	FragmentID  pgtype.UUID   `json:"fragment_id"`
	Name        string        `json:"name"`
	Content     string        `json:"content"`
	BaseVersion pgtype.Int4   `json:"base_version"`
	Ids         []pgtype.UUID `json:"ids"`
}

func (q *Queries) PushFragmentUpdate(ctx context.Context, arg PushFragmentUpdateParams) ([]ProjectGuideFragment, error) {
	rows, err := q.db.Query(ctx, pushFragmentUpdate,
		arg.FragmentID,
		arg.Name,
		arg.Content,
		arg.BaseVersion,
		arg.Ids,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGuideFragment
	for rows.Next() {
		var i ProjectGuideFragment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FragmentID,
			&i.Name,
			&i.Content,
			&i.BaseVersion,
			&i.LocallyModified,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetProjectGuideFragmentToBase = `-- name: ResetProjectGuideFragmentToBase :one
UPDATE project_guide_fragments pgf SET
    name = tf.name,
    content = tf.content,
    base_version = tf.version,
    locally_modified = false,
    updated_at = now()
FROM template_fragments tf
WHERE pgf.id = $1 AND pgf.fragment_id = tf.id
RETURNING pgf.id, pgf.project_id, pgf.fragment_id, pgf.name, pgf.content, pgf.base_version, pgf.locally_modified, pgf.position, pgf.created_at, pgf.updated_at
`

func (q *Queries) ResetProjectGuideFragmentToBase(ctx context.Context, id pgtype.UUID) (ProjectGuideFragment, error) {
	row := q.db.QueryRow(ctx, resetProjectGuideFragmentToBase, id)
	var i ProjectGuideFragment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FragmentID,
		&i.Name,
		&i.Content,
		&i.BaseVersion,
		&i.LocallyModified,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setProjectGuideFragmentPosition = `-- name: SetProjectGuideFragmentPosition :exec
UPDATE project_guide_fragments SET position = $2
WHERE id = $1
`

type SetProjectGuideFragmentPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	Position int32       `json:"position"`
}

func (q *Queries) SetProjectGuideFragmentPosition(ctx context.Context, arg SetProjectGuideFragmentPositionParams) error {
	_, err := q.db.Exec(ctx, setProjectGuideFragmentPosition, arg.ID, arg.Position)
	return err
}

const updateProjectGuideFragment = `-- name: UpdateProjectGuideFragment :one
UPDATE project_guide_fragments SET
    name = $2,
    content = $3,
    locally_modified = (fragment_id IS NOT NULL),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, fragment_id, name, content, base_version, locally_modified, position, created_at, updated_at
`

type UpdateProjectGuideFragmentParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateProjectGuideFragment(ctx context.Context, arg UpdateProjectGuideFragmentParams) (ProjectGuideFragment, error) {
	row := q.db.QueryRow(ctx, updateProjectGuideFragment, arg.ID, arg.Name, arg.Content)
	var i ProjectGuideFragment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FragmentID,
		&i.Name,
		&i.Content,
		&i.BaseVersion,
		&i.LocallyModified,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
