// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (team_id, name, description, status, lead_id, priority, target_date, template_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, name, description, status, lead_id, target_date, priority, template_id, created_at
`

type CreateProjectParams struct {
	TeamID      pgtype.UUID `json:"team_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	LeadID      pgtype.UUID `json:"lead_id"`
	Priority    int16       `json:"priority"`
	TargetDate  pgtype.Date `json:"target_date"`
	TemplateID  pgtype.UUID `json:"template_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.LeadID,
		arg.Priority,
		arg.TargetDate,
		arg.TemplateID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.LeadID,
		&i.TargetDate,
		&i.Priority,
		&i.TemplateID,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT
    p.id, p.team_id, p.name, p.description, p.status, p.lead_id, p.target_date, p.priority, p.template_id, p.created_at,
    u.name AS lead_name,
    t.name AS template_name,
    count(i.id)::int AS issue_count,
    count(i.id) FILTER (WHERE i.status = 'done')::int AS done_count
FROM projects p
LEFT JOIN users u ON u.id = p.lead_id
LEFT JOIN templates t ON t.id = p.template_id
LEFT JOIN issues i ON i.project_id = p.id
WHERE p.id = $1
GROUP BY p.id, u.name, t.name
`

type GetProjectRow struct {
	ID           pgtype.UUID        `json:"id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	LeadID       pgtype.UUID        `json:"lead_id"`
	TargetDate   pgtype.Date        `json:"target_date"`
	Priority     int16              `json:"priority"`
	TemplateID   pgtype.UUID        `json:"template_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LeadName     pgtype.Text        `json:"lead_name"`
	TemplateName pgtype.Text        `json:"template_name"`
	IssueCount   int32              `json:"issue_count"`
	DoneCount    int32              `json:"done_count"`
}

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.LeadID,
		&i.TargetDate,
		&i.Priority,
		&i.TemplateID,
		&i.CreatedAt,
		&i.LeadName,
		&i.TemplateName,
		&i.IssueCount,
		&i.DoneCount,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    p.id, p.team_id, p.name, p.description, p.status, p.lead_id, p.target_date, p.priority, p.template_id, p.created_at,
    u.name AS lead_name,
    t.name AS template_name,
    count(i.id)::int AS issue_count,
    count(i.id) FILTER (WHERE i.status = 'done')::int AS done_count
FROM projects p
LEFT JOIN users u ON u.id = p.lead_id
LEFT JOIN templates t ON t.id = p.template_id
LEFT JOIN issues i ON i.project_id = p.id
WHERE p.team_id = $1
GROUP BY p.id, u.name, t.name
ORDER BY p.created_at
`

type ListProjectsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	LeadID       pgtype.UUID        `json:"lead_id"`
	TargetDate   pgtype.Date        `json:"target_date"`
	Priority     int16              `json:"priority"`
	TemplateID   pgtype.UUID        `json:"template_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LeadName     pgtype.Text        `json:"lead_name"`
	TemplateName pgtype.Text        `json:"template_name"`
	IssueCount   int32              `json:"issue_count"`
	DoneCount    int32              `json:"done_count"`
}

func (q *Queries) ListProjects(ctx context.Context, teamID pgtype.UUID) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.LeadID,
			&i.TargetDate,
			&i.Priority,
			&i.TemplateID,
			&i.CreatedAt,
			&i.LeadName,
			&i.TemplateName,
			&i.IssueCount,
			&i.DoneCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name = $2,
    description = $3,
    status = $4,
    lead_id = $5,
    priority = $6,
    target_date = $7
WHERE id = $1
RETURNING id, team_id, name, description, status, lead_id, target_date, priority, template_id, created_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	LeadID      pgtype.UUID `json:"lead_id"`
	Priority    int16       `json:"priority"`
	TargetDate  pgtype.Date `json:"target_date"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.LeadID,
		arg.Priority,
		arg.TargetDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.LeadID,
		&i.TargetDate,
		&i.Priority,
		&i.TemplateID,
		&i.CreatedAt,
	)
	return i, err
}
