// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetIssue(ctx context.Context, id pgtype.UUID) (GetIssueRow, error)
	GetIssueByNumber(ctx context.Context, arg GetIssueByNumberParams) (GetIssueByNumberRow, error)
	GetProject(ctx context.Context, id pgtype.UUID) (GetProjectRow, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetTeam(ctx context.Context, id pgtype.UUID) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error)
	ListCycles(ctx context.Context, teamID pgtype.UUID) ([]ListCyclesRow, error)
	ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error)
	ListLabels(ctx context.Context, teamID pgtype.UUID) ([]Label, error)
	ListProjects(ctx context.Context, teamID pgtype.UUID) ([]ListProjectsRow, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateIssueDetails(ctx context.Context, arg UpdateIssueDetailsParams) (Issue, error)
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error)
	UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
