// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, key)
VALUES ($1, $2)
RETURNING id, name, key, next_issue_number, created_at
`

type CreateTeamParams struct {
	Name string `json:"name"`
	Key  string `json:"key"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Key)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.NextIssueNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, key, next_issue_number, created_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.NextIssueNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, key, next_issue_number, created_at FROM teams ORDER BY name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.NextIssueNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams SET name = $2 WHERE id = $1
RETURNING id, name, key, next_issue_number, created_at
`

type UpdateTeamNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamName, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Key,
		&i.NextIssueNumber,
		&i.CreatedAt,
	)
	return i, err
}
