// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTemplateFragment = `-- name: AddTemplateFragment :exec
INSERT INTO template_fragment_links (template_id, fragment_id, position)
VALUES (
    $1,
    $2,
    COALESCE((SELECT max(position) + 1 FROM template_fragment_links WHERE template_id = $1), 0)
)
ON CONFLICT DO NOTHING
`

type AddTemplateFragmentParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	FragmentID pgtype.UUID `json:"fragment_id"`
}

func (q *Queries) AddTemplateFragment(ctx context.Context, arg AddTemplateFragmentParams) error {
	_, err := q.db.Exec(ctx, addTemplateFragment, arg.TemplateID, arg.FragmentID)
	return err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, description, created_by, created_at, updated_at
`

type CreateTemplateParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.Name, arg.Description, arg.CreatedBy)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT t.id, t.name, t.description, t.created_by, t.created_at, t.updated_at, u.name AS author_name
FROM templates t
LEFT JOIN users u ON u.id = t.created_by
WHERE t.id = $1
`

type GetTemplateRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  pgtype.Text        `json:"author_name"`
}

func (q *Queries) GetTemplate(ctx context.Context, id pgtype.UUID) (GetTemplateRow, error) {
	row := q.db.QueryRow(ctx, getTemplate, id)
	var i GetTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listTemplateFragmentsForStamp = `-- name: ListTemplateFragmentsForStamp :many
SELECT f.id, f.name, f.category, f.content, f.version, f.created_by, f.created_at, f.updated_at, tfl.position
FROM template_fragment_links tfl
JOIN template_fragments f ON f.id = tfl.fragment_id
WHERE tfl.template_id = $1
ORDER BY tfl.position
`

type ListTemplateFragmentsForStampRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Category  pgtype.Text        `json:"category"`
	Content   string             `json:"content"`
	Version   int32              `json:"version"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Position  int32              `json:"position"`
}

// Full fragment content for every fragment linked to a template, in
// composition order — used when a Project is created from this template.
func (q *Queries) ListTemplateFragmentsForStamp(ctx context.Context, templateID pgtype.UUID) ([]ListTemplateFragmentsForStampRow, error) {
	rows, err := q.db.Query(ctx, listTemplateFragmentsForStamp, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplateFragmentsForStampRow
	for rows.Next() {
		var i ListTemplateFragmentsForStampRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateLinks = `-- name: ListTemplateLinks :many
SELECT
    tfl.template_id,
    tfl.fragment_id,
    tfl.position,
    f.name,
    f.category
FROM template_fragment_links tfl
JOIN template_fragments f ON f.id = tfl.fragment_id
WHERE tfl.template_id = $1
ORDER BY tfl.position
`

type ListTemplateLinksRow struct {
	TemplateID pgtype.UUID `json:"template_id"`
	FragmentID pgtype.UUID `json:"fragment_id"`
	Position   int32       `json:"position"`
	Name       string      `json:"name"`
	Category   pgtype.Text `json:"category"`
}

func (q *Queries) ListTemplateLinks(ctx context.Context, templateID pgtype.UUID) ([]ListTemplateLinksRow, error) {
	rows, err := q.db.Query(ctx, listTemplateLinks, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplateLinksRow
	for rows.Next() {
		var i ListTemplateLinksRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.FragmentID,
			&i.Position,
			&i.Name,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT t.id, t.name, t.description, t.created_by, t.created_at, t.updated_at, u.name AS author_name
FROM templates t
LEFT JOIN users u ON u.id = t.created_by
ORDER BY t.name
`

type ListTemplatesRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  pgtype.Text        `json:"author_name"`
}

func (q *Queries) ListTemplates(ctx context.Context) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplatesRow
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTemplateFragment = `-- name: RemoveTemplateFragment :exec
DELETE FROM template_fragment_links WHERE template_id = $1 AND fragment_id = $2
`

type RemoveTemplateFragmentParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	FragmentID pgtype.UUID `json:"fragment_id"`
}

func (q *Queries) RemoveTemplateFragment(ctx context.Context, arg RemoveTemplateFragmentParams) error {
	_, err := q.db.Exec(ctx, removeTemplateFragment, arg.TemplateID, arg.FragmentID)
	return err
}

const setTemplateFragmentPosition = `-- name: SetTemplateFragmentPosition :exec
UPDATE template_fragment_links SET position = $3
WHERE template_id = $1 AND fragment_id = $2
`

type SetTemplateFragmentPositionParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	FragmentID pgtype.UUID `json:"fragment_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) SetTemplateFragmentPosition(ctx context.Context, arg SetTemplateFragmentPositionParams) error {
	_, err := q.db.Exec(ctx, setTemplateFragmentPosition, arg.TemplateID, arg.FragmentID, arg.Position)
	return err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_by, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate, arg.ID, arg.Name, arg.Description)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
