// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: template_fragments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplateFragment = `-- name: CreateTemplateFragment :one
INSERT INTO template_fragments (name, category, content, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, category, content, version, created_by, created_at, updated_at
`

type CreateTemplateFragmentParams struct {
	Name      string      `json:"name"`
	Category  pgtype.Text `json:"category"`
	Content   string      `json:"content"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTemplateFragment(ctx context.Context, arg CreateTemplateFragmentParams) (TemplateFragment, error) {
	row := q.db.QueryRow(ctx, createTemplateFragment,
		arg.Name,
		arg.Category,
		arg.Content,
		arg.CreatedBy,
	)
	var i TemplateFragment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplateFragment = `-- name: DeleteTemplateFragment :exec
DELETE FROM template_fragments WHERE id = $1
`

func (q *Queries) DeleteTemplateFragment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplateFragment, id)
	return err
}

const getTemplateFragment = `-- name: GetTemplateFragment :one
SELECT f.id, f.name, f.category, f.content, f.version, f.created_by, f.created_at, f.updated_at, u.name AS author_name
FROM template_fragments f
LEFT JOIN users u ON u.id = f.created_by
WHERE f.id = $1
`

type GetTemplateFragmentRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Category   pgtype.Text        `json:"category"`
	Content    string             `json:"content"`
	Version    int32              `json:"version"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	AuthorName pgtype.Text        `json:"author_name"`
}

func (q *Queries) GetTemplateFragment(ctx context.Context, id pgtype.UUID) (GetTemplateFragmentRow, error) {
	row := q.db.QueryRow(ctx, getTemplateFragment, id)
	var i GetTemplateFragmentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listFragmentUsage = `-- name: ListFragmentUsage :many
SELECT
    pgf.id AS project_guide_fragment_id,
    p.id AS project_id,
    p.name AS project_name,
    pgf.locally_modified,
    pgf.base_version
FROM project_guide_fragments pgf
JOIN projects p ON p.id = pgf.project_id
WHERE pgf.fragment_id = $1
ORDER BY p.name
`

type ListFragmentUsageRow struct {
	ProjectGuideFragmentID pgtype.UUID `json:"project_guide_fragment_id"`
	ProjectID              pgtype.UUID `json:"project_id"`
	ProjectName            string      `json:"project_name"`
	LocallyModified        bool        `json:"locally_modified"`
	BaseVersion            pgtype.Int4 `json:"base_version"`
}

func (q *Queries) ListFragmentUsage(ctx context.Context, fragmentID pgtype.UUID) ([]ListFragmentUsageRow, error) {
	rows, err := q.db.Query(ctx, listFragmentUsage, fragmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFragmentUsageRow
	for rows.Next() {
		var i ListFragmentUsageRow
		if err := rows.Scan(
			&i.ProjectGuideFragmentID,
			&i.ProjectID,
			&i.ProjectName,
			&i.LocallyModified,
			&i.BaseVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateFragments = `-- name: ListTemplateFragments :many
SELECT f.id, f.name, f.category, f.content, f.version, f.created_by, f.created_at, f.updated_at, u.name AS author_name
FROM template_fragments f
LEFT JOIN users u ON u.id = f.created_by
ORDER BY f.name
`

type ListTemplateFragmentsRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Category   pgtype.Text        `json:"category"`
	Content    string             `json:"content"`
	Version    int32              `json:"version"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	AuthorName pgtype.Text        `json:"author_name"`
}

func (q *Queries) ListTemplateFragments(ctx context.Context) ([]ListTemplateFragmentsRow, error) {
	rows, err := q.db.Query(ctx, listTemplateFragments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplateFragmentsRow
	for rows.Next() {
		var i ListTemplateFragmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Content,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateFragment = `-- name: UpdateTemplateFragment :one
UPDATE template_fragments SET
    name = $2,
    category = $3,
    content = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, name, category, content, version, created_by, created_at, updated_at
`

type UpdateTemplateFragmentParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Category pgtype.Text `json:"category"`
	Content  string      `json:"content"`
}

func (q *Queries) UpdateTemplateFragment(ctx context.Context, arg UpdateTemplateFragmentParams) (TemplateFragment, error) {
	row := q.db.QueryRow(ctx, updateTemplateFragment,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Content,
	)
	var i TemplateFragment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
