// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createView = `-- name: CreateView :one
INSERT INTO views (owner_id, name, definition, shared)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, definition, shared, created_at
`

type CreateViewParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	Name       string      `json:"name"`
	Definition []byte      `json:"definition"`
	Shared     bool        `json:"shared"`
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRow(ctx, createView,
		arg.OwnerID,
		arg.Name,
		arg.Definition,
		arg.Shared,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Definition,
		&i.Shared,
		&i.CreatedAt,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM views WHERE id = $1 AND owner_id = $2
`

type DeleteViewParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteView(ctx context.Context, arg DeleteViewParams) error {
	_, err := q.db.Exec(ctx, deleteView, arg.ID, arg.OwnerID)
	return err
}

const listViews = `-- name: ListViews :many
SELECT id, owner_id, name, definition, shared, created_at FROM views WHERE owner_id = $1 OR shared = true ORDER BY created_at
`

func (q *Queries) ListViews(ctx context.Context, ownerID pgtype.UUID) ([]View, error) {
	rows, err := q.db.Query(ctx, listViews, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Definition,
			&i.Shared,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateView = `-- name: UpdateView :one
UPDATE views SET name = $3, definition = $4, shared = $5
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, definition, shared, created_at
`

type UpdateViewParams struct {
	ID         pgtype.UUID `json:"id"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Name       string      `json:"name"`
	Definition []byte      `json:"definition"`
	Shared     bool        `json:"shared"`
}

func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) (View, error) {
	row := q.db.QueryRow(ctx, updateView,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Definition,
		arg.Shared,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Definition,
		&i.Shared,
		&i.CreatedAt,
	)
	return i, err
}
