// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkLogs = `-- name: CountWorkLogs :one
SELECT count(*)::int AS total
FROM work_logs w
WHERE
    ($1::uuid IS NULL OR w.project_id = $1)
    AND ($2::uuid IS NULL OR w.author_id = $2)
    AND ($3::text IS NULL OR w.source = $3)
    AND ($4::timestamptz IS NULL OR w.created_at >= $4)
    AND ($5::timestamptz IS NULL OR w.created_at < $5)
    AND (
        $6::text IS NULL
        OR to_tsvector('english', w.title || ' ' || w.body) @@ websearch_to_tsquery('english', $6)
    )
`

type CountWorkLogsParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Source      pgtype.Text        `json:"source"`
	CreatedFrom pgtype.Timestamptz `json:"created_from"`
	CreatedTo   pgtype.Timestamptz `json:"created_to"`
	Search      pgtype.Text        `json:"search"`
}

func (q *Queries) CountWorkLogs(ctx context.Context, arg CountWorkLogsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkLogs,
		arg.ProjectID,
		arg.AuthorID,
		arg.Source,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
	)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createWorkLog = `-- name: CreateWorkLog :one
INSERT INTO work_logs (project_id, author_id, source, title, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, author_id, source, title, body, created_at
`

type CreateWorkLogParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	Source    string      `json:"source"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
}

func (q *Queries) CreateWorkLog(ctx context.Context, arg CreateWorkLogParams) (WorkLog, error) {
	row := q.db.QueryRow(ctx, createWorkLog,
		arg.ProjectID,
		arg.AuthorID,
		arg.Source,
		arg.Title,
		arg.Body,
	)
	var i WorkLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkLog = `-- name: GetWorkLog :one
SELECT w.id, w.project_id, w.author_id, w.source, w.title, w.body, w.created_at, u.name AS author_name, p.name AS project_name
FROM work_logs w
JOIN users u ON u.id = w.author_id
JOIN projects p ON p.id = w.project_id
WHERE w.id = $1
`

type GetWorkLogRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Source      string             `json:"source"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AuthorName  string             `json:"author_name"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) GetWorkLog(ctx context.Context, id pgtype.UUID) (GetWorkLogRow, error) {
	row := q.db.QueryRow(ctx, getWorkLog, id)
	var i GetWorkLogRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Source,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorName,
		&i.ProjectName,
	)
	return i, err
}

const listProjectWorkLogs = `-- name: ListProjectWorkLogs :many
SELECT w.id, w.project_id, w.author_id, w.source, w.title, w.body, w.created_at, u.name AS author_name, p.name AS project_name
FROM work_logs w
JOIN users u ON u.id = w.author_id
JOIN projects p ON p.id = w.project_id
WHERE w.project_id = $1
ORDER BY w.created_at DESC
`

type ListProjectWorkLogsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Source      string             `json:"source"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AuthorName  string             `json:"author_name"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListProjectWorkLogs(ctx context.Context, projectID pgtype.UUID) ([]ListProjectWorkLogsRow, error) {
	rows, err := q.db.Query(ctx, listProjectWorkLogs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectWorkLogsRow
	for rows.Next() {
		var i ListProjectWorkLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AuthorID,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkLogs = `-- name: ListWorkLogs :many
SELECT w.id, w.project_id, w.author_id, w.source, w.title, w.body, w.created_at, u.name AS author_name, p.name AS project_name
FROM work_logs w
JOIN users u ON u.id = w.author_id
JOIN projects p ON p.id = w.project_id
WHERE
    ($1::uuid IS NULL OR w.project_id = $1)
    AND ($2::uuid IS NULL OR w.author_id = $2)
    AND ($3::text IS NULL OR w.source = $3)
    AND ($4::timestamptz IS NULL OR w.created_at >= $4)
    AND ($5::timestamptz IS NULL OR w.created_at < $5)
    AND (
        $6::text IS NULL
        OR to_tsvector('english', w.title || ' ' || w.body) @@ websearch_to_tsquery('english', $6)
    )
ORDER BY w.created_at DESC
LIMIT $8 OFFSET $7
`

type ListWorkLogsParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Source      pgtype.Text        `json:"source"`
	CreatedFrom pgtype.Timestamptz `json:"created_from"`
	CreatedTo   pgtype.Timestamptz `json:"created_to"`
	Search      pgtype.Text        `json:"search"`
	OffsetCount int32              `json:"offset_count"`
	LimitCount  int32              `json:"limit_count"`
}

type ListWorkLogsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Source      string             `json:"source"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AuthorName  string             `json:"author_name"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListWorkLogs(ctx context.Context, arg ListWorkLogsParams) ([]ListWorkLogsRow, error) {
	rows, err := q.db.Query(ctx, listWorkLogs,
		arg.ProjectID,
		arg.AuthorID,
		arg.Source,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Search,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkLogsRow
	for rows.Next() {
		var i ListWorkLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AuthorID,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
